# Generated by Django 5.2.1 on 2025-06-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0002_alter_client_id_alter_clientstatus_id_alter_note_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='patronymic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
