# Generated by Django 5.2.1 on 2025-06-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0004_note_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
