# Generated by Django 5.2.1 on 2025-06-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0006_interaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Transactions'},
        ),
    ]
